### ISSUE TITLE
Split the mod please?

### ISSUE THREAD

**Issue by wfswanepoel** [DavidHGillen/Satisfactory-AB_FluidExtras#1]
Hello!

I love the idea to have more different pipe options, it is something that I would love to use but there is already a mod that package fluids for us and it is working amazingly.

Is it possible that you can split this in two separate mods?

here is the mod that already package fluids for us. https://ficsit.app/mod/8WJptSVNSH3xmp

**Comment by DavidHGillen** [comment]
I understand where you're coming from; however, there's a maintenance overhead to running several mods. I'm not looking to increase the paperwork I have to do to make content. I've got a couple of other ideas for things that can expand out the mod too so the difference will get further as time goes on.

I don't plan on splitting it anytime soon, but the source content is here for you to do as you will so long as there's proper attribution :)
