### ISSUE TITLE
Junctions not appearing in build menu

### ISSUE THREAD

**Issue by Ferwrech** [DavidHGillen/Satisfactory-AB_FluidExtras#10]
Junctions are not appearing on my build menu, I tried deleting my build menu mods and even using only FuildExtras as the only mod on a new Profile and an unmodded savefile. Any way to fix this?

**Comment by DavidHGillen** [comment]
For the record: The junctions need to be unlocked in packages form the Awesome sink. If you're on a dedicated server then there can be issues with it not showing up in the buy menu. but will work once purchased. So do it locally and upload the save. Sorry for the inconvenience but it's not my bug :D
