### ISSUE TITLE
No EntryWidgetClass specified ...

### ISSUE THREAD

**Issue by MartensMalsero** [DavidHGillen/Satisfactory-AB_FluidExtras#11]
Satisfactory version: 1.0
Dedicated server: Yes

When loading the mod and trying to open the Server Manager, the error message mentioned in the title appears (see screenshot). I am using.

![image](https://github.com/user-attachments/assets/a55bcc2a-33e3-4529-9e44-c9b1240ee87b)

**Comment by DavidHGillen** [comment]
Currently debugging this with others. Happening to several mods. Thanks for the report and we'll let you know.

**Comment by DavidHGillen** [comment]
This should be fully resolved as of like 1.0.4 but I recommend testing on 1.0.7 as that should have all the bug fixes this chain started.
