### ISSUE TITLE
Crash on game start after 1.0.0.5 update

### ISSUE THREAD

**Issue by ItsTBGK** [DavidHGillen/Satisfactory-AB_FluidExtras#15]
Hello, after installing the last update, my game as been crashing on startup. When i remove this mod from the folder though, the game starts right up. This makes me think that the mod is making my game crash, but i don't know enough about coding and all that to understand what the problem is.

Version: 377620, IsEditor: No, IsPerforceBuild: No, BuildConfiguration: Shipping, Launcher: Steam, NetMode: -, IsUsingMods: Yes, IsSaveGameEdited: No

Assertion failed: ObjectA == nullptr || ObjectA.IsA<UClass>() [File:C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\PropertyClass.cpp] [Line: 193]

FactoryGameSteam_Engine_Win64_Shipping!UBlueprintGeneratedClass::BuildCustomPropertyListForPostConstruction() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\Engine\Private\BlueprintGeneratedClass.cpp:904]
FactoryGameSteam_Engine_Win64_Shipping!UBlueprintGeneratedClass::UpdateCustomPropertyListForPostConstruction() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\Engine\Private\BlueprintGeneratedClass.cpp:1022]
FactoryGameSteam_Engine_Win64_Shipping!UBlueprintGeneratedClass::SerializeDefaultObject() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\Engine\Private\BlueprintGeneratedClass.cpp:570]
FactoryGameSteam_CoreUObject_Win64_Shipping!FAsyncPackage2::EventDrivenSerializeExport() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\CoreUObject\Private\Serialization\AsyncLoading2.cpp:6371]
FactoryGameSteam_CoreUObject_Win64_Shipping!FAsyncPackage2::Event_ProcessExportBundle() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\CoreUObject\Private\Serialization\AsyncLoading2.cpp:5804]
FactoryGameSteam_CoreUObject_Win64_Shipping!FEventLoadNode2::Execute() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\CoreUObject\Private\Serialization\AsyncLoading2.cpp:4320]
FactoryGameSteam_CoreUObject_Win64_Shipping!FAsyncLoadEventQueue2::ExecuteSyncLoadEvents() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\CoreUObject\Private\Serialization\AsyncLoading2.cpp:4508]
FactoryGameSteam_CoreUObject_Win64_Shipping!FAsyncLoadingThread2::Run() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\CoreUObject\Private\Serialization\AsyncLoading2.cpp:7665]
FactoryGameSteam_Core_Win64_Shipping!FRunnableThreadWin::Run() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\Core\Private\Windows\WindowsRunnableThread.cpp:149]

**Comment by ItsTBGK** [comment]
I tried a fresh install of the mod, but i still get a crash. This time however i have a different error code

Version: 377620, IsEditor: No, IsPerforceBuild: No, BuildConfiguration: Shipping, Launcher: Steam, NetMode: -, IsUsingMods: Yes, IsSaveGameEdited: No

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x000000003f800038

FactoryGameSteam_CoreUObject_Win64_Shipping!FObjectPtr::IsA() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ObjectPtr.cpp:87]
FactoryGameSteam_CoreUObject_Win64_Shipping!FClassProperty::Identical() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\PropertyClass.cpp:193]
FactoryGameSteam_Engine_Win64_Shipping!UBlueprintGeneratedClass::BuildCustomPropertyListForPostConstruction() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\Engine\Private\BlueprintGeneratedClass.cpp:904]
FactoryGameSteam_Engine_Win64_Shipping!UBlueprintGeneratedClass::UpdateCustomPropertyListForPostConstruction() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\Engine\Private\BlueprintGeneratedClass.cpp:1022]
FactoryGameSteam_Engine_Win64_Shipping!UBlueprintGeneratedClass::SerializeDefaultObject() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\Engine\Private\BlueprintGeneratedClass.cpp:570]
FactoryGameSteam_CoreUObject_Win64_Shipping!FAsyncPackage2::EventDrivenSerializeExport() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\CoreUObject\Private\Serialization\AsyncLoading2.cpp:6371]
FactoryGameSteam_CoreUObject_Win64_Shipping!FAsyncPackage2::Event_ProcessExportBundle() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\CoreUObject\Private\Serialization\AsyncLoading2.cpp:5804]
FactoryGameSteam_CoreUObject_Win64_Shipping!FEventLoadNode2::Execute() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\CoreUObject\Private\Serialization\AsyncLoading2.cpp:4320]
FactoryGameSteam_CoreUObject_Win64_Shipping!FAsyncLoadEventQueue2::ExecuteSyncLoadEvents() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\CoreUObject\Private\Serialization\AsyncLoading2.cpp:4508]
FactoryGameSteam_CoreUObject_Win64_Shipping!FAsyncLoadingThread2::Run() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\CoreUObject\Private\Serialization\AsyncLoading2.cpp:7665]
FactoryGameSteam_Core_Win64_Shipping!FRunnableThreadWin::Run() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\Core\Private\Windows\WindowsRunnableThread.cpp:149]

**Comment by DavidHGillen** [comment]
Latest should resolve this, reopen if it hasn't.
