### ISSUE TITLE
Satisfactory crash since the update of 04/11/24

### ISSUE THREAD

**Issue by clement-krv** [DavidHGillen/Satisfactory-AB_FluidExtras#16]
Hello,

On this day of 04 November 2024, there was a Satisfactory update, which since then the mods are incompatible, regardless of the version used 1.0.7 or earlier. We are therefore stuck in our part that uses a lot of the new features offered by this mod. Please fix this as soon as possible for the comfort of our FICSIT employees.

Sincerely,

Clément KERVICHE

**Comment by DavidHGillen** [comment]
I will fix as soon as possible, please note I need the updated SML to perform my fixes if it's anything more than a recompile.

**Comment by fihnakis** [comment]
Just came here to comment the same, looking forward to using this great mod again soon

**Comment by DavidHGillen** [comment]
Latest is working fine for me, reopen if there's issues.
