### ISSUE TITLE
Game crash on save load after the recent v1.0.1.0 update / build 382498

### ISSUE THREAD

**Issue by Arapacana** [DavidHGillen/Satisfactory-AB_FluidExtras#19]
First of all, thanks for this awesome mod! Unfortunately, it looks like if this mod is enabled, my save game crashes on load after the update to v1.0.1.0.  I went through and disabled my mods and enabled one by one; I can enable everything but Fluid Extras.  The game will spend a long time loading the save, then quit to desktop.

Mod profile:
[ModProfile.zip](https://github.com/user-attachments/files/17964331/ModProfile.zip)

Thank you!

**Comment by DavidHGillen** [comment]
A new build has been pushed that is rebuilt with 1.0.1.0 in the hopes that fixes the rare users who are getting crashes now. If it doesn't please re-open this. But since the recompile should fix it I'll close this for now!

**Comment by Arapacana** [comment]
You, sir, are a scholar and a gentleman. Thank you for the fix, which is working.
