### ISSUE TITLE
?GetColorSlot_Implementation@AFGBuildable@@UEAAEXZ is not found in the library of dynamic link.

### ISSUE THREAD

**Issue by sLevasseur** [DavidHGillen/Satisfactory-AB_FluidExtras#3]
Hello David,
After Update 5 on early access, i'm gettting this error message whever i launch the game with mods activated (through Satisfactory Mod Manager)

![Screenshot 2021-11-24 211052-1](https://user-images.githubusercontent.com/37228391/143309691-e32fedfa-25e9-4f35-9035-2e416628a46d.png)
![Screenshot 2021-11-24 211052](https://user-images.githubusercontent.com/37228391/143309698-3b513bc9-ea6f-4318-a784-11a89557ddc0.png)
r)

I checked the decompiled FactoryGame-AB_FluidExtras-Win64-Shipping.dll and i can see the function, so i'm surprised modulde can't be loaded.

Maybe i'm not in the right place, sorry in advance and congratulations for your mod David !
Thank you

**Comment by DavidHGillen** [comment]
These are the errors you get when things aren't up to date. I just reconfirmed that with the game, SML (3.2.0) and Fluid Extras (0.7.0) all up to date then it works fine. If you're still having issues after getting everything up to date please reopen this with the debug logs from SML.
