### ISSUE TITLE
All custom pipe junctions become white at certain distance

### ISSUE THREAD

**Issue by Krzeszny** [DavidHGillen/Satisfactory-AB_FluidExtras#4]
I haven't bothered with reporting this bug for months but here I am at last.

If you go approx. 100 meters from any junction from this mod, it becomes white. If you go back to closer than 75 meters, it becomes colored again. Happens always, U5 and U6. Doesn't happen to vanilla junctions.

**Comment by DavidHGillen** [comment]
It's and issue with the LODS. I spotted it myself but forgot to look into. Thanks for reporting it I'll be keeping it in mind.
