### ISSUE TITLE
Can't color pipe junctions if color brightness is 0

### ISSUE THREAD

**Issue by Krzeszny** [DavidHGillen/Satisfactory-AB_FluidExtras#5]
If I choose a color that has 0 brightness, all custom pipe junctions ignore that color. 

To color them black, I must choose a color that has 0.01 or more brightness, as seen here:
![FactoryGame-Win64-Shipping_3fDy7HmSpf](https://user-images.githubusercontent.com/10529134/190877888-a43e726a-7483-4fd8-b016-50a0bb2004fb.png)

Happens always, U5 and U6. 

P.S. This is the second and last bug I've found while using this mod for months. It's a great mod.

**Comment by DavidHGillen** [comment]
That's a bug I introduced into the modding tools to improve workflow. it's the fact the colour is #000000 that's causing something to think it's unset and revert to ficsit brand defaults. It's come up a few times, and someone might of found a better workflow hack. but even if you just set the colour to #010101 it wont occur and in PBR you shouldn't be using sub #202020 anyway in theory -cough- -cough-
I'll keep this open to remind myself to look into it again.

**Comment by DavidHGillen** [comment]
SML updates contain fix
