### ISSUE TITLE
Milestone not appearing in HUB

### ISSUE THREAD

**Issue by KyriadosX** [DavidHGillen/Satisfactory-AB_FluidExtras#8]
The Tier 3 Milestone: "Extra Pipe Junctions" does not show up in the HUB on current save. Will be making subsequent saves to see if it is a one-off bug. Wanted to make a report note just in case

**Comment by DavidHGillen** [comment]
With the expanded roster of junctions I've removed the milestone and transitioned to the awesome shop for several bundles. As a legacy user I didn't revoke your right the use the junctions already enabled in the save, but you would have to buy the bundles in the awesome shop now.
